title: Alexandre F. Magalhães
description: "Cloud Architect"
author:
  name: "Alexandre F. Magalhães"
  email: "alexandrefm@gmail.com"
  url: "https://afmagalhaes.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Alexandre F. Magalhães"
year : "2020"
