title: afmagalhaes.net
description: "Site pessoal"
author:
  name: "Alexandre F. Magalhães"
  email: "alexandrefm@gmail.com"
  url: "https://afmagalhaes.net"

#baseurl: /

source: .
destination: ./_site
#permalink: /:title
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Alexandre F. Magalhães"
year : "2020"
